version: "3.8"

services:
  db:
    container_name: db
    image: postgres:13-alpine
    volumes:
      - ./db/postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./server/:/usr/src/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./web/:/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server

volumes:
  postgres_data:
